---
abstract: 'interface to the Untappd API'
author:
  - 'Rafael Oliveira Lopes <rlopes@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Untappd-API
no_index:
  directory:
    - t
    - inc
requires:
  Hijk: '0'
  Moo: '0'
  Test::More: '0.88'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Untappd-API
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rafaelol/untappd-api
version: '0.01'
